development:
    adapter: mysql2
   encoding: utf8
  reconnect: false
   database: backlogflow_development
       pool: 5
   username: root
   password: backlogflow
     socket: /var/run/mysqld/mysqld.sock

test:
    adapter: mysql2
   encoding: utf8
  reconnect: false
   database: backlogflow_test
       pool: 5
   username: root
   password: backlogflow
     socket: /var/run/mysqld/mysqld.sock

production:
    adapter: mysql2
   encoding: utf8
  reconnect: false
   database: backlogflow_production
       pool: 5
   username: root
   password: backlogflow
     socket: /var/run/mysqld/mysqld.sock